include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_return_type_for_catch_error: ignore
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
  exclude:
    - "*.md"
    - "lib/gen/**"
    - "lib/core/localization/generated/**"

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - prefer_final_fields
    - use_super_parameters
    - file_names
    - avoid_unnecessary_containers
    - avoid_print
