// SettingsModel
// Generated by Flutter Bunny Cli🐰

class SettingsModel {
  final String id;
  final String name;
  // Add more fields as needed

  SettingsModel({
    required this.id,
    required this.name,
  });

  factory SettingsModel.fromJson(Map<String, dynamic> json) {
    return SettingsModel(
      id: json['id'],
      name: json['name'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
    };
  }
}
