// SettingsView
// Generated by Flutter Bunny Cli🐰
import 'package:flutter/material.dart';

class SettingsView extends StatelessWidget {
  const SettingsView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // Use state management here to connect with viewmodel
    return Scaffold(
      appBar: AppBar(
        title: Text('Settings'),
      ),
      body: Center(
        child: Text('Settings View'),
      ),
    );
  }
}
