// UserProfileView
// Generated by Flutter Bunny Cli🐰
import 'package:flutter/material.dart';

class UserProfileView extends StatelessWidget {
  const UserProfileView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // Use state management here to connect with viewmodel
    return Scaffold(
      appBar: AppBar(
        title: const Text('UserProfile'),
      ),
      body: const Center(
        child: Text('UserProfile View'),
      ),
    );
  }
}
