// UserProfileView
// Generated by Flutter Bunny Cli🐰
import 'package:flutter/material.dart';
import 'package:stacked/stacked.dart';
import '../viewmodels/user_profile_viewmodel.dart';

class UserProfileView extends StackedView<UserProfileViewModel> {
  const UserProfileView({super.key});

  @override
  Widget builder(
    BuildContext context,
    UserProfileViewModel viewModel,
    Widget? child,
  ) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Perfil'),
      ),
      body: ListView(
        padding: const EdgeInsets.all(16.0),
        children: [
          const CircleAvatar(
            radius: 50,
            child: Icon(Icons.person, size: 50),
          ),
          const SizedBox(height: 24),
          const Divider(),
          ListTile(
            leading: const Icon(Icons.info_outline),
            title: const Text('Sobre'),
            trailing: const Icon(Icons.chevron_right),
            onTap: viewModel.navigateToAbout,
          ),
          ListTile(
            leading: const Icon(Icons.bug_report_outlined),
            title: const Text('Relatar um Problema'),
            trailing: const Icon(Icons.chevron_right),
            onTap: () => viewModel.showFeedback(context),
          ),
        ],
      ),
    );
  }

  @override
  UserProfileViewModel viewModelBuilder(BuildContext context) =>
      UserProfileViewModel();
}
