// AuthenticationView
// Generated by Flutter Bunny Cli🐰
import 'package:flutter/material.dart';

class AuthenticationView extends StatelessWidget {
  const AuthenticationView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // Use state management here to connect with viewmodel
    return Scaffold(
      appBar: AppBar(
        title: Text('Authentication'),
      ),
      body: Center(
        child: Text('Authentication View'),
      ),
    );
  }
}
