// AuthenticationView
// Generated by Flutter Bunny Cli🐰
import 'package:flutter/material.dart';

class AuthenticationView extends StatelessWidget {
  const AuthenticationView({super.key});

  @override
  Widget build(BuildContext context) {
    // Use state management here to connect with viewmodel
    return Scaffold(
      appBar: AppBar(
        title: const Text('Authentication'),
      ),
      body: const Center(
        child: Text('Authentication View'),
      ),
    );
  }
}
