// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBvLlZjf0eAxQbjRCKgWGr4xsRzKqdeZY',
    appId: '1:86790721181:web:1ac47f755219c4d9db0e74',
    messagingSenderId: '86790721181',
    projectId: 'admin-we-barato',
    authDomain: 'admin-we-barato.firebaseapp.com',
    storageBucket: 'admin-we-barato.firebasestorage.app',
    measurementId: 'G-T9MQSZYE73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4omasO0fQtAa0LyJZMi4p-F_4SniEqpc',
    appId: '1:86790721181:android:19238f375ace9f62db0e74',
    messagingSenderId: '86790721181',
    projectId: 'admin-we-barato',
    storageBucket: 'admin-we-barato.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBvLlZjf0eAxQbjRCKgWGr4xsRzKqdeZY',
    appId: '1:86790721181:web:8a683fe1c409f183db0e74',
    messagingSenderId: '86790721181',
    projectId: 'admin-we-barato',
    authDomain: 'admin-we-barato.firebaseapp.com',
    storageBucket: 'admin-we-barato.firebasestorage.app',
    measurementId: 'G-KP4V9S19Y0',
  );
}
