// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWTrAjgpPiv4mPN19MM1rJhEvkPu4E7bY',
    appId: '1:802718084241:web:5fbee23d65b1901c2de330',
    messagingSenderId: '802718084241',
    projectId: 'caiaia01',
    authDomain: 'caiaia01.firebaseapp.com',
    databaseURL: 'https://caiaia01-default-rtdb.firebaseio.com',
    storageBucket: 'caiaia01.firebasestorage.app',
    measurementId: 'G-ZF6VF7Y2PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF0NxGyrNIj1_Sc2ALJN_Ejg_xsYpb5-0',
    appId: '1:802718084241:android:d0aa2422a70a87872de330',
    messagingSenderId: '802718084241',
    projectId: 'caiaia01',
    databaseURL: 'https://caiaia01-default-rtdb.firebaseio.com',
    storageBucket: 'caiaia01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCktxDXI1lID2xJ5wMAD7UCUzimVu6zbwg',
    appId: '1:802718084241:ios:26c0177eba0b91662de330',
    messagingSenderId: '802718084241',
    projectId: 'caiaia01',
    databaseURL: 'https://caiaia01-default-rtdb.firebaseio.com',
    storageBucket: 'caiaia01.firebasestorage.app',
    iosBundleId: 'app.biblia.eusou',
  );
}
