// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/deep_understanding/data/models/analysis_session.dart';
import 'features/deep_understanding/data/models/verse_embedding.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 795792232932813392),
    name: 'AnalysisSession',
    lastPropertyId: const obx_int.IdUid(14, 1739034297125974665),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4821624473580079210),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3130829822837491982),
        name: 'sessionId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 4877655845860484749),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1424789162859295557),
        name: 'query',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7689589007852527787),
        name: 'totalItems',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9111247414510825074),
        name: 'processedItems',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6486561405252083748),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5511242620464933864),
        name: 'error',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8387865822389228614),
        name: 'result',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1201828426570961329),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5509001783183294485),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1675110034444379766),
        name: 'embeddingDurationMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 9006372578112263410),
        name: 'searchDurationMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1976364457849664017),
        name: 'summaryDurationMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1739034297125974665),
        name: 'totalDurationMillis',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7284105156833445624),
    name: 'VerseEmbedding',
    lastPropertyId: const obx_int.IdUid(5, 7530142049878187324),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7323912265193026170),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 716111193588331249),
        name: 'verseId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 7415064644571484510),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 362692223089821853),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6370311787834391221),
        name: 'vector',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(4, 5219079436045896860),
        hnswParams: obx_int.ModelHnswParams(dimensions: 3072),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7530142049878187324),
        name: 'sessionId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 6117475879194710042),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 7284105156833445624),
    lastIndexId: const obx_int.IdUid(4, 5219079436045896860),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AnalysisSession: obx_int.EntityDefinition<AnalysisSession>(
      model: _entities[0],
      toOneRelations: (AnalysisSession object) => [],
      toManyRelations: (AnalysisSession object) => {},
      getId: (AnalysisSession object) => object.id,
      setId: (AnalysisSession object, int id) {
        object.id = id;
      },
      objectToFB: (AnalysisSession object, fb.Builder fbb) {
        final sessionIdOffset = fbb.writeString(object.sessionId);
        final queryOffset = fbb.writeString(object.query);
        final statusOffset = fbb.writeString(object.status);
        final errorOffset = object.error == null
            ? null
            : fbb.writeString(object.error!);
        final resultOffset = object.result == null
            ? null
            : fbb.writeString(object.result!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sessionIdOffset);
        fbb.addOffset(2, queryOffset);
        fbb.addInt64(3, object.totalItems);
        fbb.addInt64(4, object.processedItems);
        fbb.addOffset(5, statusOffset);
        fbb.addOffset(6, errorOffset);
        fbb.addOffset(7, resultOffset);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.embeddingDurationMillis);
        fbb.addInt64(11, object.searchDurationMillis);
        fbb.addInt64(12, object.summaryDurationMillis);
        fbb.addInt64(13, object.totalDurationMillis);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final sessionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final queryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final totalItemsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final processedItemsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final errorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final resultParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final embeddingDurationMillisParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 24);
        final searchDurationMillisParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 26);
        final summaryDurationMillisParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 28);
        final totalDurationMillisParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 30);
        final object = AnalysisSession(
          sessionId: sessionIdParam,
          query: queryParam,
          totalItems: totalItemsParam,
          processedItems: processedItemsParam,
          status: statusParam,
          error: errorParam,
          result: resultParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          embeddingDurationMillis: embeddingDurationMillisParam,
          searchDurationMillis: searchDurationMillisParam,
          summaryDurationMillis: summaryDurationMillisParam,
          totalDurationMillis: totalDurationMillisParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    VerseEmbedding: obx_int.EntityDefinition<VerseEmbedding>(
      model: _entities[1],
      toOneRelations: (VerseEmbedding object) => [],
      toManyRelations: (VerseEmbedding object) => {},
      getId: (VerseEmbedding object) => object.id,
      setId: (VerseEmbedding object, int id) {
        object.id = id;
      },
      objectToFB: (VerseEmbedding object, fb.Builder fbb) {
        final verseIdOffset = fbb.writeString(object.verseId);
        final contentOffset = fbb.writeString(object.content);
        final vectorOffset = fbb.writeListFloat32(object.vector);
        final sessionIdOffset = fbb.writeString(object.sessionId);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, verseIdOffset);
        fbb.addOffset(2, contentOffset);
        fbb.addOffset(3, vectorOffset);
        fbb.addOffset(4, sessionIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final verseIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final vectorParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final sessionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = VerseEmbedding(
          verseId: verseIdParam,
          content: contentParam,
          vector: vectorParam,
          sessionId: sessionIdParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AnalysisSession] entity fields to define ObjectBox queries.
class AnalysisSession_ {
  /// See [AnalysisSession.id].
  static final id = obx.QueryIntegerProperty<AnalysisSession>(
    _entities[0].properties[0],
  );

  /// See [AnalysisSession.sessionId].
  static final sessionId = obx.QueryStringProperty<AnalysisSession>(
    _entities[0].properties[1],
  );

  /// See [AnalysisSession.query].
  static final query = obx.QueryStringProperty<AnalysisSession>(
    _entities[0].properties[2],
  );

  /// See [AnalysisSession.totalItems].
  static final totalItems = obx.QueryIntegerProperty<AnalysisSession>(
    _entities[0].properties[3],
  );

  /// See [AnalysisSession.processedItems].
  static final processedItems = obx.QueryIntegerProperty<AnalysisSession>(
    _entities[0].properties[4],
  );

  /// See [AnalysisSession.status].
  static final status = obx.QueryStringProperty<AnalysisSession>(
    _entities[0].properties[5],
  );

  /// See [AnalysisSession.error].
  static final error = obx.QueryStringProperty<AnalysisSession>(
    _entities[0].properties[6],
  );

  /// See [AnalysisSession.result].
  static final result = obx.QueryStringProperty<AnalysisSession>(
    _entities[0].properties[7],
  );

  /// See [AnalysisSession.createdAt].
  static final createdAt = obx.QueryDateProperty<AnalysisSession>(
    _entities[0].properties[8],
  );

  /// See [AnalysisSession.updatedAt].
  static final updatedAt = obx.QueryDateProperty<AnalysisSession>(
    _entities[0].properties[9],
  );

  /// See [AnalysisSession.embeddingDurationMillis].
  static final embeddingDurationMillis =
      obx.QueryIntegerProperty<AnalysisSession>(_entities[0].properties[10]);

  /// See [AnalysisSession.searchDurationMillis].
  static final searchDurationMillis = obx.QueryIntegerProperty<AnalysisSession>(
    _entities[0].properties[11],
  );

  /// See [AnalysisSession.summaryDurationMillis].
  static final summaryDurationMillis =
      obx.QueryIntegerProperty<AnalysisSession>(_entities[0].properties[12]);

  /// See [AnalysisSession.totalDurationMillis].
  static final totalDurationMillis = obx.QueryIntegerProperty<AnalysisSession>(
    _entities[0].properties[13],
  );
}

/// [VerseEmbedding] entity fields to define ObjectBox queries.
class VerseEmbedding_ {
  /// See [VerseEmbedding.id].
  static final id = obx.QueryIntegerProperty<VerseEmbedding>(
    _entities[1].properties[0],
  );

  /// See [VerseEmbedding.verseId].
  static final verseId = obx.QueryStringProperty<VerseEmbedding>(
    _entities[1].properties[1],
  );

  /// See [VerseEmbedding.content].
  static final content = obx.QueryStringProperty<VerseEmbedding>(
    _entities[1].properties[2],
  );

  /// See [VerseEmbedding.vector].
  static final vector = obx.QueryHnswProperty<VerseEmbedding>(
    _entities[1].properties[3],
  );

  /// See [VerseEmbedding.sessionId].
  static final sessionId = obx.QueryStringProperty<VerseEmbedding>(
    _entities[1].properties[4],
  );
}
