// BibliaModel
// Generated by Flutter Bunny Cli🐰

class BibliaModel {
  final String id;
  final String name;
  // Add more fields as needed

  BibliaModel({
    required this.id,
    required this.name,
  });

  factory BibliaModel.fromJson(Map<String, dynamic> json) {
    return BibliaModel(
      id: json['id'],
      name: json['name'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
    };
  }
}
