// Base view model
// Generated by Flutter Bunny Cli🐰

abstract class BaseViewModel {
  // Base view model functionality
  // This would typically include common properties and methods
  // for all view models in the application

  bool isLoading = false;
  String? errorMessage;

  void setLoading(bool loading) {
    isLoading = loading;
    // Notify listeners - implementation depends on state management
  }

  void setError(String? error) {
    errorMessage = error;
    // Notify listeners - implementation depends on state management
  }
}
