name: CI

on:
  push:
    branches: [ main, master, '007-bottom-navigation-bar' ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Unit Tests & Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.38.5
          cache: true

      - name: Install dependencies (Root)
        run: flutter pub get --verbosity=error

      - name: Run build_runner (Root)
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # - name: Analyze (Root)
      #   run: flutter analyze

      - name: Run tests (Root)
        run: flutter test

      - name: Install dependencies (bible_handler)
        working-directory: packages/bible_handler
        run: flutter pub get

      - name: Analyze (bible_handler)
        working-directory: packages/bible_handler
        run: flutter analyze

      - name: Run tests (bible_handler)
        working-directory: packages/bible_handler
        run: flutter test
