name: Web Build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Create .env file
        run: echo "$ENV_FILE_BASE64" | base64 --decode > .env
        env:
          ENV_FILE_BASE64: ${{ secrets.ENV_FILE_BASE64 }}

      - name: Build web (smoke)
        run: flutter build web --no-tree-shake-icons
